#!/bin/zsh

###############
# TRANSCODING #
###############
h264() {
	ffmpeg -i "$1" -c:v libx264 -c:a copy "${1%.*}.mp4"
}

h265() {
	ffmpeg -i "$1" -c:v libx265 -c:a copy "${1%.*}".mp4
}

webm() {
	ffmpeg -i "$1" -c vp9 -b:v 0 -crf 40 "${1%.*}".webm
}

########
# MISC #
########
# Get audio codec
audio_codec() {
	ffprobe -v error -select_streams a:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 $1
}

# Extract out metadata for audio frames into a csv file with headers
audio_frames() {
	headers="pkt_pts_time,pkt_duration_time,pkt_size"
	ffprobe_output=$(ffprobe -select_streams a -show_entries "frame=${headers}" -print_format csv -i $1)
	echo "frame,${headers}\n${ffprobe_output}" >$1.csv
}

# Extract raw audio into file, takes in additional optional argument for output file name
extract_audio() {
	file=$1
	codec=$(acodec $1)
	new_file=${2:-"${file%.*}.${codec}"}
	ffmpeg -i $file -vn -acodec copy $new_file
}

# Get video codec
video_codec() {
	ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 $1
}
