#!/bin/zsh

# Commit all and push
function gacp() {
	if [[ $# -eq 0 ]]; then
		git add -A && git commit --amend --no-edit && git push --force-with-lease
	else
		git add -A && git commit -m "$1" && git push
	fi
}

# Delete branch matching regex
function gbd() {
  	git branch --list "$1" | xargs -n 1 git branch -D
}

# Fuzzy git checkout for branches
function gch() {
	git checkout "${1:-$(git branch --all | fzf | awk '{print $1}')}"
}

# Git fetch checkout
function gfc() {
	git fetch origin "$1" && git checkout FETCH_HEAD -b "$1"
}

# Fuzzy git merge for branches
function gmr() {
	git merge "${1:-$(git branch --all | fzf | awk '{print $1}')}"
}

# Fuzzy git rebase for branches
function grb() {
	git rebase "${1:-$(git branch --all | fzf | awk '{print $1}')}"
}

# Git fetch, rebase and force push
function gfrp() {
	git fetch origin "$1":"$1" && git rebase "$1" && git push --force-with-lease
}

# Reset with remote
function grr() {
	local branch=${1:-$(git branch --show-current)}
	git fetch origin "$branch" && git reset --hard "origin/$branch"
}
