#!/bin/zsh

# Commit all and push
function gcamp() {
	git commit -a -m $1 && git push
}

# Fuzzy git checkout for branches
function gch() {
	git checkout "${1:-$(git branch --all | fzf | awk '{print $1}')}"
}

# Fuzzy git merge for branches
function gmr() {
	git merge "${1:-$(git branch --all | fzf awk '{print $1}')}"
}

# Fuzzy git rebase for branches
function grb() {
	git rebase "${1:-$(git branch --all | fzf | awk '{print $1}')}"
}

# Reset with remote
function grr() {
	branch=${1:-$(git branch --show-current)}
	git fetch origin "$branch" && git reset --hard origin/$branch
}
