#!/bin/zsh

# Bazel
alias b="bazel"
alias bt="bazel test"

# Clear
alias c="clear"

# Colorize
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# FFmpeg
alias ffm="ffmpeg"
alias ffp="ffprobe -hide_banner"

# General
alias reload="source ~/.zshrc"

# Git
alias g="git"
alias ga="git add"
alias gaa="git add -A"
alias gb="git branch --color=always"
alias gbi="git bisect"
alias gc="git commit"
alias gcb="git checkout -b"
alias gco="git checkout"
alias gd="git diff"
alias gf="git fetch"
alias gfo="git fetch origin"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gll="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --author="$(git config user.name)""
alias gm="git merge"
alias gp="git push"
alias gpl="git pull"
alias gr="git reset"
alias grba="git rebase --abort"
alias grbc="git rebase --continue"
alias grh="git reset --hard"
alias gs="git status"
alias gsu="git status --untracked-files=no"

# GPAC
alias mb="mp4box"

# Ls (Exa)
alias l="exa --icons --group-directories-first"
alias ll="exa --icons --group-directories-first -l -a"

# UNSW CSE
alias cse="ssh z5308213@login.cse.unsw.edu.au"

# Youtube dl
alias ydl="youtube-dl"
alias ydlea="youtube-dl --extract-audio"
