#!/bin/zsh

# Clear
alias c="clear"

# Colorize
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# GPAC
alias mb="mp4box"

# FFmpeg
alias ffm="ffmpeg"
alias ffp="ffprobe -hide_banner"

# Git
alias g="git"
alias ga="git add"
alias gaa="git add -A"
alias gb="git branch --color=always"
alias gc="git commit"
alias gcb="git checkout -b"
alias gco="git checkout"
alias gd="git diff"
alias gf="git fetch"
alias gl="git log"
alias gll="git log --author="$(git config user.name)""
alias gm="git merge"
alias gp="git push"
alias gpl="git pull"
alias gs="git status"

# Ls (Exa)
alias l="exa --icons --group-directories-first"
alias ll="exa --icons --group-directories-first -l -a"

# UNSW CSE
alias cse="ssh z5308213@login.cse.unsw.edu.au"
