#!/bin/sh

copy() {
    cp $HOME/dev/dotfiles/$1 $2
}

setup() {
    source $HOME/dev/dotfiles/$1
}

symblink() {
    ln -s $HOME/dev/dotfiles/$1 $2
}

# Copy files
copy .vimrc ~/.vimrc

# Run files
setup aliases
setup functions

# Symlink files
