#!/bin/bash
# Dotfiles setup. Works on macOS (zsh) and Linux (bash).
# On Linux with bash: clone repo, then from bash run: source ~/dev/dotfiles/setup
# (or add that line to ~/.bashrc). Aliases/functions are written to work in both shells.

add_to_path() {
    export PATH="$PATH:$HOME/dev/dotfiles/$1"
}

copy() {
    cp $HOME/dev/dotfiles/$1 $2
}

setup() {
    source $HOME/dev/dotfiles/$1
}

symlink() {
    [[ -e $2 ]] || ln -s $HOME/dev/dotfiles/$1 $2
}

setup_dir() {
    for entry in $(ls $HOME/dev/dotfiles/$1); do
        setup "$1/$entry"
    done
}

# Add to path
add_to_path scripts

# Copy files
copy .vimrc ~/.vimrc

# Run files
setup aliases
setup_dir functions

# Symlink files
symlink tmux.conf ~/.tmux.conf
